Setup portfolio one
tchasinga/setup-portfolio pull request #3
Opened 2023-03-25 21:34 UTC by tchasinga

Remember to document your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
Create a new GitHub repo.
Create a new branch according to the [GitHub flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md) rules.
Add a .gitignore file.
Add node_modules to gitignore file.
Set up [a linter for HTML and CSS](https://github.com/microverseinc/linters-config) and make sure that any files that are not relevant are ignored by git.
Add descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.
Add 3 files (each one in a separate commit):
A .html file that includes a header with the text "Hello Microverse!". Use h1 tag for that.
A .css file that includes one class with styles for your header (make it in your favorite color).
A test.md file with the text "This file should be ignored by git".
Make sure that the last file is actually ignored by git and is not present in your GitHub repository.
Open a pull request.

2023-03-25 22:32 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @tchasinga, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 22:32 UTC, bobb-Rob commented on index.html
> +          <ul>
- [ ] You did everything very well. Kudo 👏🏾 👏🏾 👏🏾 

The image below shows the typo error in your about section
![image](https://user-images.githubusercontent.com/84156714/227744798-44a5c588-6e94-4745-93b0-8cf4d3660a62.png)

2023-03-25 22:32 UTC, bobb-Rob commented on index.html
> +                <li class="programming">CSS</li>
- [ ] The container of this _**works section**_ is a section tag. This is semantically correct as it helps assistive technologies to make meaning of your webpage elements. 
- [ ] The arrangement of the cards in the cards container should use CSS grid to align them responsively.

**Kindly fix this.**

2023-03-25 22:32 UTC, bobb-Rob commented on index.html
> +       </div>
- [ ] The container of this about me section should be a `section` tag for semantic reasons.
- [ ] This about section container should use CSS flexbox to align elements.

2023-03-25 22:32 UTC, bobb-Rob commented on index.html
> +            <h1>About Myself</h1>
You may consider using another of the `hx` tag, maybe `h2` or `h3` etc. Usually, it is advisable to have one `h1` tag in a document if you want your headline page title to rank well in google search.

2023-03-25 22:32 UTC, bobb-Rob commented on index.html
> +             <li>
- [ ] The technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`.  The technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list `ul` and each of them a `li`

2023-03-26 19:00 UTC, tchasinga commented
bobb-Rob Good evening I've make your all corrections and I'm wait your validation it will be helpful, that will help me to move forward Thank you enough

2023-03-27 08:36 UTC, Abenezer-Tilahun requested changes
Hi @tchasinga    , 

Great job for implemented  the some of the project requirement  , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ No Linters error
✔️ You used correct Git Hub-Flow.
✔️ Good commit messages
✔️ Professional  README 



![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 08:36 UTC, Abenezer-Tilahun commented on index.html
> +      </div>
- [ ] Kindly I recommend you to use `section` tag for Work section , It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.

2023-03-27 08:36 UTC, Abenezer-Tilahun commented on index.html
>        </div>
- [ ] Kindly I recommend you to use `section` tag for About section , It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.

2023-03-27 08:36 UTC, Abenezer-Tilahun commented on index.html
> +          </ul>
- [ Optional ] Kindly I recommend you to use `header` tag only for Toolbar(Nav bar),  This way will be semantically correct and the screen readers and other technologies will thank you. I know that this activity is from the first mobile setup project but kindly implemented for the best practices of HTML code.

2023-03-27 08:36 UTC, Abenezer-Tilahun commented on index.html
> +        </nav>
- [ Optional ] Kindly I recommend you to use `section` tag for Headline section , It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.  I know that this activity is from the first mobile setup project but kindly implemented for the best practices of HTML code.

2023-03-27 08:36 UTC, Abenezer-Tilahun commented on index.html
> +          <h1 class="paragraphHOne">LET'US CONNECT</h1>
- [ ] Kindly I recommend you to use a `a` or `h2` or `h3 ` tag for LET'US CONNECT, This way will be semantically correct and the screen readers and other technologies will thank you.  I know that this activity is from the first mobile setup project but kindly implemented for the best practices of HTML code.

2023-03-27 08:36 UTC, Abenezer-Tilahun commented on index.html
> +            <h1>About Myself</h1>
- [ ] Kindly I recommend you to use `hx `(h2 )tag for "About Myself" , because for the purpose of search and optimization, it's better to have only one `h1` tag in your HTML code which is for only the headline section.

2023-03-27 08:36 UTC, Abenezer-Tilahun commented on index.html
> +          </div>
- [ ] As stated in the project requirement , You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). So Kindly adjust the margins of the "See Project"  ti's a little bit out of the cards box.
Your Cards for project List Design :
 
![Capture](https://user-images.githubusercontent.com/93598189/227887537-6ae298ce-7478-4f04-8973-ec28b763bbd6.PNG)

2023-03-27 08:54 UTC, tchasinga commented on index.html
> +      </div>
why do you change every single time your requirements... in the first time you ask me do all logic code in one section, 
after that , you still keeping another disappointing, sorry 🙏 for that , I think I don't have the save skills as but the purpose of every language programming is to work first, About this requirement :
 **"Kindly I recommend you to use section tag for Work section , It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info."**

I can say I've done it as well but I'll try to review it... because also I've to another challenge, thank you

2023-03-27 09:04 UTC, Abenezer-Tilahun commented on index.html
> +      </div>
Hello @tchasinga I am really sorry if i make you to feel just like this but I am not really sure how  in the first time who ask you to do all logic code in one `section` but When I review your code I followed the Micro-verse guideline So  based on that you have to implemented the suggested changes. Yeah I see that you implemented most of the project requirement and your design is looks perfect, So Please implement the suggested changes before submit for the second review,

2023-03-27 11:35 UTC, tchasinga commented
I've already submit your requirements just I'm waiting your validation,
before you I'd another Code viewer, and he ask me to submit logic in the
same section

On Mon, Mar 27, 2023 at 1:31 PM Tchasinga Jacques <
***@***.***> wrote:

> Okay let me Put logic in one section
> except  the HEADER it will stay outside the cards section
>
> On Mon, Mar 27, 2023 at 11:04 AM Abenezer-Tilahun <
> ***@***.***> wrote:
>
>> ***@***.**** commented on this pull request.
>> ------------------------------
>>
>> In index.html
>> <https://github.com/tchasinga/setup-portfolio/pull/3#discussion_r1149011151>
>> :
>>
>> > +            <div class="reader">
>> +              <p>
>> +                A daily selection of privately <br> personalized reads; no accounts or
>> +                sign-ups required.
>> +              </p>
>> +            </div>
>> +
>> +            <div class="languagedetails">
>> +              <ul>
>> +                <li class="programming">
>> +                  <h4>HTML</h4>
>> +                </li>
>> +                <li class="programming">
>> +                  <h4>CSS</h4>
>> +                </li>
>> +                <li class="programming" id="javascript">
>> +                 <h4>JavaScript</h4>
>> +                </li>
>> +              </ul>
>> +            </div>
>> +            <div class="seen">
>> +              <button><h4>See project</h4></button>
>> +            </div>
>> +          </div>
>> +        </div>
>> +
>> +        <div class="generaContainerTwo">
>> +          <div class="cardsTage">
>> +            <img src="Img/Snapshoot Portfoliotwo.png" alt="" />
>> +            <h2>Jack</h2>
>> +            <ul>
>> +              <li class="Canopyparams">CANOPY</li>
>> +              <img src="Icon/Counter.png" class="sameImg" alt="">
>> +              <li class="moveClassing"> Band end dev</li>
>> +              <img src="Icon/Counter.png" class="sameImge" alt="">
>> +              <li class="moveClass">2015</li>
>> +            </ul>
>> +            <div class="reader">
>> +              <p>
>> +                A daily selection of privately <br> personalized reads; no accounts or
>> +                sign-ups required.
>> +              </p>
>> +            </div>
>> +
>> +            <div class="languagedetails">
>> +              <ul>
>> +                <li class="programming">
>> +                  <h4>HTML</h4>
>> +                </li>
>> +                <li class="programming">
>> +                  <h4>CSS</h4>
>> +                </li>
>> +                <li class="programming" id="javascript">
>> +                 <h4>JavaScript</h4>
>> +                </li>
>> +              </ul>
>> +            </div>
>> +            <div class="seen">
>> +              <button><h4>See project</h4></button>
>> +            </div>
>> +          </div>
>> +        </div>
>> +
>> +        <div class="generaContainerTwo">
>> +          <div class="cardsTage">
>> +            <img src="Img/Snapshoot PortfolioEnd.png" alt="" />
>> +            <h2>Multi-post Stories</h2>
>> +            <ul>
>> +              <li class="Canopyparams">CANOPY</li>
>> +              <img src="Icon/Counter.png" class="sameImg" alt="">
>> +              <li class="moveClassing"> Band end dev</li>
>> +              <img src="Icon/Counter.png" class="sameImge" alt="">
>> +              <li class="moveClass">2015</li>
>> +            </ul>
>> +            <div class="reader">
>> +              <p>
>> +                A daily selection of privately <br> personalized reads; no accounts or
>> +                sign-ups required.
>> +              </p>
>> +            </div>
>> +
>> +            <div class="languagedetails">
>> +              <ul>
>> +                <li class="programming">
>> +                  <h4>HTML</h4>
>> +                </li>
>> +                <li class="programming">
>> +                  <h4>CSS</h4>
>> +                </li>
>> +                <li class="programming" id="javascript">
>> +                 <h4>JavaScript</h4>
>> +                </li>
>> +              </ul>
>> +            </div>
>> +            <div class="seen">
>> +              <button><h4>See project</h4></button>
>> +            </div>
>> +          </div>
>> +        </div>
>> +      </div>
>>
>> Hello @tchasinga <https://github.com/tchasinga> I am really sorry if i
>> make you to feel just like this but I am not really sure how in the first
>> time who ask you to do all logic code in one section but When I review
>> your code I followed the Micro-verse guideline So based on that you have to
>> implemented the suggested changes. Yeah I see that you implemented most of
>> the project requirement and your design is looks perfect, So Please
>> implement the suggested changes before submit for the second review,
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/tchasinga/setup-portfolio/pull/3#discussion_r1149011151>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A43RMQE5EXG6ZAOE7MUB663W6FJ3PANCNFSM6AAAAAAWHYHLS4>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2023-03-27 11:57 UTC, franclobo approved these changes
Hi @tchasinga, 

# STATUS: APPROVED 😃 

![git-merge](https://user-images.githubusercontent.com/58642949/227935064-893942bf-e3d9-45f3-beed-7fa62e4007d5.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Github flow ✔️ 
- Good UI ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 11:57 UTC, franclobo commented on index.html
> +          <h1 class="paragraphHOne">LET'US CONNECT</h1>
- **[OPTIONAL]** I marked this as optional because this section is not part of this milestone. Well done implementing `hx` tag, but as requested by the previous code reviewer he recommended using **h2** or **h3** because you have used **h1** for the principal title and we can use it just once for the best practices of HTML and CSS please 🙏🏽 change this **h1** to **h2** or **h3**, however, I highly recommend to use the `a` tag because `LET'US CONNECT` represents a link to the contact form.

2023-03-27 11:57 UTC, franclobo commented on index.html
> +            <h3>LET'US CONNECT</h3>
- **[OPTIONAL]**  I highly recommend using the `a` tag because `LET'US CONNECT` represents a link to the contact form for the best practices of HTML and CSS.

2023-03-27 11:59 UTC, merged